# Generated by Django 4.2.16 on 2024-10-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_joueurs', '0008_alter_player_age_alter_player_club_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(default='', help_text='Enter a unique email address for the player.', max_length=254, verbose_name='Email Address'),
        ),
    ]
