# Generated by Django 4.2.16 on 2024-10-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_joueurs', '0011_alter_player_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='info',
            field=models.TextField(blank=True, help_text='Additional information about the video.', null=True, verbose_name='Info'),
        ),
    ]
