# Generated by Django 4.2.16 on 2024-10-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_joueurs', '0013_alter_player_age_alter_player_club_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
