# Generated by Django 4.2.16 on 2024-10-17 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_joueurs', '0014_payment_remaining_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='season',
            field=models.CharField(choices=[('2022/2023', '2022/2023'), ('2023/2024', '2023/2024'), ('2024/2025', '2024/2025'), ('2025/2026', '2025/2026')], default='2024/2025', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='gestion_joueurs.video'),
        ),
    ]
