# Generated by Django 4.2.16 on 2024-10-20 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_joueurs', '0021_alter_invoice_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='gestion_joueurs.video'),
        ),
    ]
