# Generated by Django 4.2.16 on 2024-10-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_joueurs', '0023_alter_invoice_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Virement bancaire'), ('la_poste', 'La poste')], max_length=50, null=True),
        ),
    ]
