# Generated by Django 4.2.16 on 2024-10-26 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_joueurs', '0028_expense_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Transport', 'Transport'), ('Entertainement', 'Loisirs'), ('Internet', 'Internet'), ('marketing', 'Marketing'), ('operational', 'Operational'), ('salary', 'Salary'), ('equipment', 'Equipment'), ('other', 'Other')], default='other', max_length=100),
        ),
    ]
