# Generated by Django 4.2.16 on 2024-10-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_joueurs', '0029_alter_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
