# Generated by Django 4.2.16 on 2024-10-27 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_joueurs', '0030_video_video_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed_collab', 'Completed Collab'), ('completed', 'Completed'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
