# Generated by Django 4.2.16 on 2024-11-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_joueurs', '0035_notification_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('inter_user', 'Inter-user Notification'), ('video_process', 'Video Processing Notification'), ('financial', 'Financial Notification'), ('alert', 'Alert'), ('reminder', 'Reminder'), ('update', 'Update')], default='update', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('paid', 'Payé'), ('unpaid', 'Unpayé'), ('partially_paid', 'Partiallement Payé')], default='unpaid', max_length=20),
        ),
    ]
