# Generated by Django 4.2.16 on 2024-11-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_joueurs', '0036_notification_type_alter_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('paid', 'paid'), ('unpaid', 'unpaid'), ('partially_paid', 'partially paid')], default='unpaid', max_length=20),
        ),
    ]
