# Generated by Django 4.2.16 on 2024-11-05 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_joueurs', '0043_financialreport_total_outstanding_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialreport',
            name='net_revenue_if_all_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
