# Generated by Django 4.2.20 on 2026-04-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_joueurs', '0049_alter_invoice_id_alter_nonvideoincome_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='sportsbase_url',
            field=models.URLField(blank=True, null=True, verbose_name='SportsBase URL'),
        ),
        migrations.AddField(
            model_name='player',
            name='transfermarkt_url',
            field=models.URLField(blank=True, null=True, verbose_name='Transfermarkt URL'),
        ),
        migrations.AddField(
            model_name='video',
            name='automation_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='automation_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='delivery_mode',
            field=models.CharField(choices=[('normal', 'Normal'), ('automation', 'Automation')], default='normal', max_length=20, verbose_name='Delivery Mode'),
        ),
        migrations.AddField(
            model_name='video',
            name='processing_mode',
            field=models.CharField(choices=[('normal', 'Normal'), ('automation', 'Automation')], default='normal', max_length=20, verbose_name='Processing Mode'),
        ),
    ]
