# Generated by Django 4.2.20 on 2026-04-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_joueurs', '0050_player_sportsbase_url_player_transfermarkt_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='delivery_automation_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='delivery_automation_started',
            field=models.BooleanField(default=False),
        ),
    ]
