# Generated by Django 4.2.20 on 2026-04-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_joueurs', '0051_video_delivery_automation_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='seasons_to_process',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 saison'), (2, '2 saisons')], default=1, verbose_name='Nombre de saisons à traiter'),
        ),
    ]
