# Generated by Django 4.2.20 on 2026-04-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_joueurs', '0052_video_seasons_to_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='intro_automation_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='intro_automation_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='intro_photo',
            field=models.ImageField(blank=True, null=True, upload_to='video_intro_photos/', verbose_name='Photo Intro'),
        ),
    ]
