# Generated by Django 4.2.20 on 2026-04-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_joueurs', '0053_video_intro_automation_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='intro_automation_enabled',
            field=models.BooleanField(default=False, verbose_name='Générer la présentation'),
        ),
    ]
