# Generated by Django 4.2.20 on 2026-08-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_joueurs', '0054_video_intro_automation_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='client_portal_visible',
            field=models.BooleanField(default=True, help_text='Décochez pour conserver cette vidéo uniquement dans la gestion interne.', verbose_name='Visible dans l’espace client'),
        ),
    ]
