# Generated by Django 4.2.20 on 2026-08-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_joueurs", "0055_video_client_portal_visible"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="deadline",
            field=models.DateField(),
        ),
    ]
