from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django.core.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gestion_joueurs", "0056_alter_video_deadline"),
    ]

    operations = [
        migrations.CreateModel(
            name="SportsBaseSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True, verbose_name="Abonnement actif")),
                ("season", models.CharField(max_length=20, verbose_name="Saison actuelle")),
                ("starts_on", models.DateField(default=django.utils.timezone.localdate, verbose_name="Début de l’abonnement")),
                ("ends_on", models.DateField(blank=True, null=True, verbose_name="Fin de l’abonnement")),
                ("sync_from_date", models.DateField(blank=True, help_text="Facultatif : ignore les rencontres plus anciennes.", null=True, verbose_name="Importer à partir de la date")),
                ("first_match_id", models.CharField(blank=True, help_text="Facultatif : ce match devient le début de la saison à importer.", max_length=32, verbose_name="Premier identifiant de match SportsBase")),
                ("all_actions_enabled", models.BooleanField(default=True, verbose_name="Télécharger All Actions")),
                ("email_delivery_enabled", models.BooleanField(default=True, verbose_name="Envoyer All Actions par e-mail")),
                ("sync_interval_hours", models.PositiveSmallIntegerField(default=24, validators=[django.core.validators.MinValueValidator(1)], verbose_name="Intervalle de synchronisation (heures)")),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_state", models.CharField(choices=[("never", "Jamais synchronisé"), ("queued", "En attente"), ("running", "Synchronisation en cours"), ("success", "À jour"), ("partial", "Partiellement synchronisé"), ("failed", "Échec")], default="never", max_length=16)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_sportsbase_subscriptions", to=settings.AUTH_USER_MODEL)),
                ("player", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="sportsbase_subscription", to="gestion_joueurs.player", verbose_name="Joueur")),
            ],
            options={"verbose_name": "Abonnement Performance", "verbose_name_plural": "Abonnements Performance", "ordering": ("player__name",)},
        ),
        migrations.CreateModel(
            name="SportsBaseSeasonSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("season", models.CharField(max_length=20)),
                ("sportsbase_player_id", models.CharField(blank=True, db_index=True, max_length=32)),
                ("sportsbase_player_name", models.CharField(blank=True, max_length=160)),
                ("native_name", models.CharField(blank=True, max_length=160)),
                ("club_name", models.CharField(blank=True, max_length=160)),
                ("club_sportsbase_id", models.CharField(blank=True, max_length=32)),
                ("profile_image_url", models.URLField(blank=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("nationality", models.CharField(blank=True, max_length=100)),
                ("contract_expires", models.DateField(blank=True, null=True)),
                ("height_weight", models.CharField(blank=True, max_length=100)),
                ("national_team", models.CharField(blank=True, max_length=160)),
                ("strong_foot", models.CharField(blank=True, max_length=80)),
                ("time_on_field_percent", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("positions", models.JSONField(blank=True, default=list)),
                ("season_statistics", models.JSONField(blank=True, default=dict)),
                ("average_statistics", models.JSONField(blank=True, default=dict)),
                ("season_table_headers", models.JSONField(blank=True, default=list)),
                ("season_match_rows", models.JSONField(blank=True, default=list)),
                ("radar_metrics", models.JSONField(blank=True, default=list)),
                ("source_metadata", models.JSONField(blank=True, default=dict)),
                ("radar_png", models.BinaryField(blank=True, editable=False, null=True)),
                ("heatmap_png", models.BinaryField(blank=True, editable=False, null=True)),
                ("ball_touches_png", models.BinaryField(blank=True, editable=False, null=True)),
                ("maps_captured_at", models.DateTimeField(blank=True, null=True)),
                ("synced_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subscription", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="season_snapshots", to="sportsbase_data.sportsbasesubscription")),
            ],
            options={"ordering": ("-season",)},
        ),
        migrations.CreateModel(
            name="SportsBaseMatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sportsbase_match_id", models.CharField(max_length=32)),
                ("season", models.CharField(max_length=20)),
                ("match_date", models.DateField(blank=True, db_index=True, null=True)),
                ("competition", models.CharField(blank=True, max_length=160)),
                ("week", models.CharField(blank=True, max_length=80)),
                ("referee", models.CharField(blank=True, max_length=160)),
                ("home_team", models.CharField(blank=True, max_length=160)),
                ("home_team_id", models.CharField(blank=True, max_length=32)),
                ("away_team", models.CharField(blank=True, max_length=160)),
                ("away_team_id", models.CharField(blank=True, max_length=32)),
                ("home_score", models.SmallIntegerField(blank=True, null=True)),
                ("away_score", models.SmallIntegerField(blank=True, null=True)),
                ("lineup", models.CharField(blank=True, max_length=80)),
                ("match_url", models.URLField(blank=True)),
                ("sync_state", models.CharField(choices=[("discovered", "Détecté"), ("synced", "Statistiques synchronisées"), ("partial", "Données partielles"), ("failed", "Erreur")], default="discovered", max_length=16)),
                ("actions_state", models.CharField(choices=[("not_requested", "Non demandé"), ("queued", "À générer"), ("generating", "Génération SportsBase"), ("downloaded", "Téléchargé localement"), ("emailed", "Envoyé par e-mail"), ("failed", "Erreur")], default="not_requested", max_length=20)),
                ("local_folder_key", models.CharField(blank=True, max_length=255)),
                ("all_actions_filename", models.CharField(blank=True, max_length=255)),
                ("all_actions_downloaded_at", models.DateTimeField(blank=True, null=True)),
                ("all_actions_emailed_at", models.DateTimeField(blank=True, null=True)),
                ("delivery_error", models.TextField(blank=True)),
                ("source_metadata", models.JSONField(blank=True, default=dict)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subscription", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="matches", to="sportsbase_data.sportsbasesubscription")),
            ],
            options={"ordering": ("-match_date", "-sportsbase_match_id")},
        ),
        migrations.CreateModel(
            name="SportsBaseMatchStats",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("team_name", models.CharField(blank=True, max_length=160)),
                ("position", models.CharField(blank=True, max_length=80)),
                ("position_percentages", models.JSONField(blank=True, default=list)),
                ("minutes_played", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("index", models.IntegerField(blank=True, null=True)),
                ("team_rank", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("match_rank", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("summary_statistics", models.JSONField(blank=True, default=dict)),
                ("success_rates", models.JSONField(blank=True, default=dict)),
                ("detailed_statistics", models.JSONField(blank=True, default=dict)),
                ("team_table", models.JSONField(blank=True, default=list)),
                ("source_metadata", models.JSONField(blank=True, default=dict)),
                ("heatmap_png", models.BinaryField(blank=True, editable=False, null=True)),
                ("ball_touches_png", models.BinaryField(blank=True, editable=False, null=True)),
                ("maps_captured_at", models.DateTimeField(blank=True, null=True)),
                ("synced_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("match", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="player_stats", to="sportsbase_data.sportsbasematch")),
            ],
            options={"verbose_name": "Statistiques SportsBase du match", "verbose_name_plural": "Statistiques SportsBase des matchs"},
        ),
        migrations.CreateModel(
            name="SportsBaseSyncJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("job_type", models.CharField(choices=[("full", "Profil, saison, matchs et All Actions"), ("profile", "Profil et saison"), ("matches", "Matchs et statistiques"), ("all_actions", "All Actions manquants")], default="full", max_length=20)),
                ("status", models.CharField(choices=[("pending", "En attente"), ("running", "En cours"), ("success", "Terminé"), ("partial", "Partiel"), ("failed", "Échec")], db_index=True, default="pending", max_length=16)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("result_summary", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("requested_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="requested_sportsbase_sync_jobs", to=settings.AUTH_USER_MODEL)),
                ("subscription", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sync_jobs", to="sportsbase_data.sportsbasesubscription")),
            ],
            options={"ordering": ("created_at",)},
        ),
        migrations.AddConstraint(
            model_name="sportsbaseseasonsnapshot",
            constraint=models.UniqueConstraint(fields=("subscription", "season"), name="unique_sportsbase_subscription_season"),
        ),
        migrations.AddConstraint(
            model_name="sportsbasematch",
            constraint=models.UniqueConstraint(fields=("subscription", "sportsbase_match_id"), name="unique_sportsbase_match_per_subscription"),
        ),
    ]
