# Generated by Django 4.2.20 on 2026-08-20 22:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_joueurs', '0054_video_intro_automation_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Nom')),
                ('kind', models.CharField(choices=[('agent', 'Agence / Agent'), ('academy', 'Académie'), ('club', 'Club')], default='agent', max_length=20, verbose_name='Type')),
                ('contact_name', models.CharField(blank=True, max_length=120, verbose_name='Contact principal')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('whatsapp_number', models.CharField(blank=True, max_length=24, verbose_name='WhatsApp')),
                ('country', models.CharField(blank=True, max_length=80, verbose_name='Pays')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_portal_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organisation cliente',
                'verbose_name_plural': 'Organisations clientes',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='VideoWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('new_order', 'Nouvelle commande'), ('awaiting_deposit', 'En attente d’acompte'), ('awaiting_media', 'Matchs à recevoir'), ('downloading', 'Téléchargement SportsBase'), ('editing', 'Montage en cours'), ('client_review', 'Validation client'), ('revisions', 'Corrections demandées'), ('awaiting_balance', 'Solde à payer'), ('ready_delivery', 'Prête à livrer'), ('delivered', 'Livrée'), ('blocked', 'Bloquée')], max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('normal', 'Normale'), ('high', 'Haute'), ('urgent', 'Urgente')], default='normal', max_length=12)),
                ('progress', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('next_action', models.CharField(blank=True, max_length=240)),
                ('blocked_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_video_workflows', to=settings.AUTH_USER_MODEL)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production_workflow', to='gestion_joueurs.video')),
            ],
            options={
                'ordering': ('video__deadline', '-priority'),
            },
        ),
        migrations.CreateModel(
            name='VideoVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(blank=True, max_length=160)),
                ('preview_url', models.URLField(verbose_name='Lien de prévisualisation')),
                ('final_url', models.URLField(blank=True, verbose_name='Lien final')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'À valider'), ('changes_requested', 'Corrections demandées'), ('approved', 'Approuvée'), ('replaced', 'Remplacée')], default='pending', max_length=24)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_portal_versions', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_portal_versions', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_versions', to='gestion_joueurs.video')),
            ],
            options={
                'ordering': ('-version_number',),
            },
        ),
        migrations.CreateModel(
            name='VideoActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('note', 'Note'), ('stage', 'Étape'), ('media', 'Média'), ('version', 'Version'), ('review', 'Validation / correction'), ('payment', 'Paiement'), ('message', 'Communication')], default='note', max_length=20)),
                ('visibility', models.CharField(choices=[('internal', 'Interne'), ('client', 'Visible par le client')], default='internal', max_length=20)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_video_activities', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_activities', to='gestion_joueurs.video')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RevisionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timecode_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('comment', models.TextField()),
                ('status', models.CharField(choices=[('open', 'À traiter'), ('in_progress', 'En cours'), ('resolved', 'Résolue'), ('rejected', 'Non retenue')], default='open', max_length=20)),
                ('staff_response', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_portal_revisions', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_portal_revisions', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_requests', to='client_portal.videoversion')),
            ],
            options={
                'ordering': ('status', 'timecode_seconds', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='PortalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('player', 'Joueur'), ('agent', 'Agent'), ('academy', 'Académie / Club')], max_length=20, verbose_name='Type de compte')),
                ('display_name', models.CharField(max_length=160, verbose_name='Nom affiché')),
                ('whatsapp_number', models.CharField(blank=True, max_length=24, verbose_name='WhatsApp')),
                ('preferred_language', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('ar', 'العربية')], default='fr', max_length=5, verbose_name='Langue')),
                ('is_active', models.BooleanField(default=True, verbose_name='Accès actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_portal_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compte portail',
                'verbose_name_plural': 'Comptes portail',
                'ordering': ('display_name',),
            },
        ),
        migrations.CreateModel(
            name='PortalAccessLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_portal_access_links', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_access_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PlayerAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('player', 'Joueur'), ('representative', 'Représentant'), ('viewer', 'Lecture seule')], default='player', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_player_accesses', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_user_accesses', to='gestion_joueurs.player')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_player_accesses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('payment_url', models.URLField(blank=True, help_text='Lien créé chez le prestataire de paiement choisi.', verbose_name='Lien de paiement')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('opened', 'Lien ouvert'), ('paid', 'Payée'), ('cancelled', 'Annulée'), ('expired', 'Expirée')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_portal_payment_requests', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_payment_requests', to='gestion_joueurs.video')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrganizationPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='Référence interne')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_organization_players', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_links', to='client_portal.organization')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_organization_links', to='gestion_joueurs.player')),
            ],
            options={
                'ordering': ('player__name',),
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Responsable'), ('staff', 'Collaborateur'), ('viewer', 'Lecture seule')], default='owner', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='client_portal.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MediaSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('match', 'Match complet'), ('action', 'Action individuelle'), ('statistics', 'Statistiques'), ('photo', 'Photo / identité visuelle'), ('document', 'Document'), ('other', 'Autre')], max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('source_url', models.URLField(verbose_name='Lien du fichier ou du match')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('reviewed', 'Vérifié'), ('accepted', 'Accepté'), ('rejected', 'À remplacer')], default='new', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_portal_media_submissions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_media_submissions', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_submissions', to='gestion_joueurs.video')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('portal', 'Portail')], max_length=20)),
                ('template_key', models.CharField(blank=True, max_length=40)),
                ('recipient', models.CharField(blank=True, max_length=180)),
                ('message', models.TextField()),
                ('state', models.CharField(choices=[('draft_opened', 'Brouillon ouvert'), ('sent', 'Envoyé'), ('delivered', 'Livré'), ('failed', 'Échec'), ('received', 'Reçu')], default='draft_opened', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_communications', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_logs', to='gestion_joueurs.player')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_logs', to='gestion_joueurs.video')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AgentPlayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160, verbose_name='Nom du joueur')),
                ('transfermarkt_url', models.URLField(blank=True, verbose_name='Lien Transfermarkt')),
                ('club', models.CharField(blank=True, max_length=120, verbose_name='Club')),
                ('whatsapp_number', models.CharField(blank=True, max_length=24, verbose_name='WhatsApp')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Nouvelle'), ('reviewing', 'En vérification'), ('linked', 'Joueur associé'), ('rejected', 'Refusée')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_agent_requests', to='gestion_joueurs.player')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_requests', to='client_portal.organization')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_agent_player_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_portal_agent_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='videoversion',
            constraint=models.UniqueConstraint(fields=('video', 'version_number'), name='unique_portal_video_version_number'),
        ),
        migrations.AddConstraint(
            model_name='playeraccess',
            constraint=models.UniqueConstraint(fields=('user', 'player'), name='unique_portal_user_player_access'),
        ),
        migrations.AddConstraint(
            model_name='organizationplayer',
            constraint=models.UniqueConstraint(fields=('organization', 'player'), name='unique_portal_organization_player'),
        ),
        migrations.AddConstraint(
            model_name='organizationmembership',
            constraint=models.UniqueConstraint(fields=('organization', 'user'), name='unique_portal_organization_membership'),
        ),
    ]
