# Generated by Django 4.2.20 on 2026-08-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationplayer',
            name='ended_at',
            field=models.DateTimeField(blank=True, help_text='Renseignée lorsque le joueur n’est plus représenté par cette organisation.', null=True, verbose_name='Fin de la relation'),
        ),
    ]
