# Generated by Django 4.2 for the isolated prospects application.

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prospect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=120, verbose_name="Nom du joueur")),
                (
                    "whatsapp_number",
                    models.CharField(
                        max_length=16,
                        validators=[
                            django.core.validators.RegexValidator(
                                message=(
                                    "Saisissez un numéro WhatsApp international valide, "
                                    "par exemple +21620123456."
                                ),
                                regex="^\\+?[1-9]\\d{7,14}$",
                            )
                        ],
                        verbose_name="Numéro WhatsApp",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="Adresse e-mail")),
                ("country", models.CharField(max_length=80, verbose_name="Pays")),
                ("club", models.CharField(blank=True, max_length=120, verbose_name="Club actuel")),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("goalkeeper", "Gardien"),
                            ("defender", "Défenseur"),
                            ("midfielder", "Milieu"),
                            ("forward", "Attaquant"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Poste",
                    ),
                ),
                ("season", models.CharField(max_length=20, verbose_name="Saison")),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("highlights", "Vidéo highlights"),
                            ("video_cv", "CV vidéo"),
                            ("other", "Autre service"),
                        ],
                        max_length=20,
                        verbose_name="Service souhaité",
                    ),
                ),
                ("match_links", models.TextField(verbose_name="Liens des matchs")),
                ("desired_deadline", models.DateField(blank=True, null=True, verbose_name="Date souhaitée")),
                ("message", models.TextField(blank=True, verbose_name="Informations complémentaires")),
                ("source", models.CharField(default="Formulaire web", max_length=80, verbose_name="Source")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nouveau"),
                            ("contacted", "Contacté"),
                            ("interested", "Intéressé"),
                            ("converted", "Converti"),
                            ("lost", "Perdu"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("internal_notes", models.TextField(blank=True, verbose_name="Notes internes")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Créé le")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Modifié le")),
            ],
            options={
                "verbose_name": "Prospect vidéo",
                "verbose_name_plural": "Prospects vidéo",
                "ordering": ("-created_at",),
            },
        ),
    ]
