# Generated by Django 4.2.20 on 2026-08-20 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_joueurs', '0054_video_intro_automation_enabled'),
        ('prospects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='league',
            field=models.CharField(choices=[('L1', 'Ligue 1 Tunisie'), ('L2', 'Ligue 2 Tunisie'), ('LY', 'Libye'), ('OC', 'Autre pays')], default='OC', max_length=2, verbose_name='Championnat'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospect_requests', to='gestion_joueurs.player', verbose_name='Joueur associé'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='transfermarkt_url',
            field=models.URLField(blank=True, verbose_name='Lien Transfermarkt'),
        ),
    ]
