# Generated by Django 4.2.20 on 2026-08-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0002_prospect_date_of_birth_prospect_league_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='country',
            field=models.CharField(blank=True, max_length=80, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='match_links',
            field=models.TextField(blank=True, verbose_name='Liens des matchs'),
        ),
    ]
