# Generated by Django 4.2.16 on 2024-10-10 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion_joueurs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoeditor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='videoeditor',
            name='name',
        ),
        migrations.AddField(
            model_name='videoeditor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
