# Generated by Django 4.2.16 on 2024-10-12 11:07

import django.core.validators
from django.db import migrations, models
import gestion_joueurs.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_joueurs', '0007_alter_player_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(blank=True, help_text="Enter the player's age (must be non-negative).", null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='player',
            name='club',
            field=models.CharField(default='', help_text='Enter the club of the player.', max_length=100, verbose_name='Club Name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(default='', help_text='Enter a unique email address for the player.', max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='', help_text='Enter the name of the player.', max_length=100, verbose_name='Player Name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Enter the WhatsApp number in the format +999999999999 or 999999999.', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Le numéro de WhatsApp doit être au format +999999999999 ou 999999999.', regex='^\\+?1?\\d{9,15}$')], verbose_name='WhatsApp Number'),
        ),
        migrations.AlterField(
            model_name='video',
            name='deadline',
            field=models.DateField(validators=[gestion_joueurs.models.validate_deadline]),
        ),
    ]
