# Generated by Django 4.2.16 on 2024-10-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_joueurs', '0025_salary_expense_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='salary_paid_status',
            field=models.CharField(choices=[('not_paid', 'Not Paid'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid')], default='not_paid', max_length=20, verbose_name='Salary Payment Status'),
        ),
    ]
