# Generated by Django 4.2.16 on 2024-10-22 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_joueurs', '0026_video_salary_paid_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='description',
        ),
    ]
