# Generated by Django 4.2.16 on 2024-10-27 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_joueurs', '0031_alter_video_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
