# Generated by Django 4.2.16 on 2024-11-03 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_joueurs', '0039_notification_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_joueurs.player'),
        ),
    ]
