# Generated by Django 4.2.16 on 2024-11-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_joueurs', '0041_nonvideoincome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonvideoincome',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nonvideoincome',
            name='category',
            field=models.CharField(choices=[('freelance', 'Freelance'), ('deposit', 'Deposit'), ('coach_cv', 'CV Coach'), ('marketing', 'Marketing'), ('sponsorship', 'Sponsorship'), ('donation', 'Donation'), ('partnership', 'Partnership'), ('media', 'Media'), ('other', 'Other')], max_length=50),
        ),
    ]
