# Generated by Django 4.2.16 on 2024-11-05 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_joueurs', '0045_financialreport_global_income'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialreport',
            old_name='Global_income',
            new_name='global_income',
        ),
    ]
